/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockesp_err.h"

static const char* CMockString__esp_error_check_failed = "_esp_error_check_failed";
static const char* CMockString__esp_error_check_failed_without_abort = "_esp_error_check_failed_without_abort";
static const char* CMockString_buf = "buf";
static const char* CMockString_buflen = "buflen";
static const char* CMockString_code = "code";
static const char* CMockString_esp_err_to_name = "esp_err_to_name";
static const char* CMockString_esp_err_to_name_r = "esp_err_to_name_r";
static const char* CMockString_expression = "expression";
static const char* CMockString_file = "file";
static const char* CMockString_function = "function";
static const char* CMockString_line = "line";
static const char* CMockString_rc = "rc";

typedef struct _CMOCK_esp_err_to_name_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  const char* ReturnVal;
  esp_err_t Expected_code;

} CMOCK_esp_err_to_name_CALL_INSTANCE;

typedef struct _CMOCK_esp_err_to_name_r_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  const char* ReturnVal;
  esp_err_t Expected_code;
  char* Expected_buf;
  size_t Expected_buflen;

} CMOCK_esp_err_to_name_r_CALL_INSTANCE;

typedef struct _CMOCK__esp_error_check_failed_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t Expected_rc;
  const char* Expected_file;
  int Expected_line;
  const char* Expected_function;
  const char* Expected_expression;

} CMOCK__esp_error_check_failed_CALL_INSTANCE;

typedef struct _CMOCK__esp_error_check_failed_without_abort_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t Expected_rc;
  const char* Expected_file;
  int Expected_line;
  const char* Expected_function;
  const char* Expected_expression;

} CMOCK__esp_error_check_failed_without_abort_CALL_INSTANCE;

static struct Mockesp_errInstance
{
  CMOCK_MEM_INDEX_TYPE esp_err_to_name_CallInstance;
  CMOCK_MEM_INDEX_TYPE esp_err_to_name_r_CallInstance;
  CMOCK_MEM_INDEX_TYPE _esp_error_check_failed_CallInstance;
  CMOCK_MEM_INDEX_TYPE _esp_error_check_failed_without_abort_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockesp_err_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.esp_err_to_name_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_err_to_name);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.esp_err_to_name_r_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_esp_err_to_name_r);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock._esp_error_check_failed_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString__esp_error_check_failed);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock._esp_error_check_failed_without_abort_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString__esp_error_check_failed_without_abort);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockesp_err_Init(void)
{
  Mockesp_err_Destroy();
}

void Mockesp_err_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

const char* esp_err_to_name(esp_err_t code)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_err_to_name_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_err_to_name);
  cmock_call_instance = (CMOCK_esp_err_to_name_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_err_to_name_CallInstance);
  Mock.esp_err_to_name_CallInstance = CMock_Guts_MemNext(Mock.esp_err_to_name_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_esp_err_to_name,CMockString_code);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_code), (void*)(&code), sizeof(esp_err_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_err_to_name(CMOCK_esp_err_to_name_CALL_INSTANCE* cmock_call_instance, esp_err_t code);
void CMockExpectParameters_esp_err_to_name(CMOCK_esp_err_to_name_CALL_INSTANCE* cmock_call_instance, esp_err_t code)
{
  memcpy((void*)(&cmock_call_instance->Expected_code), (void*)(&code),
         sizeof(esp_err_t[sizeof(code) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void esp_err_to_name_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t code, const char* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_err_to_name_CALL_INSTANCE));
  CMOCK_esp_err_to_name_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_err_to_name_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_err_to_name_CallInstance = CMock_Guts_MemChain(Mock.esp_err_to_name_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_esp_err_to_name(cmock_call_instance, code);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

const char* esp_err_to_name_r(esp_err_t code, char* buf, size_t buflen)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_esp_err_to_name_r_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_esp_err_to_name_r);
  cmock_call_instance = (CMOCK_esp_err_to_name_r_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.esp_err_to_name_r_CallInstance);
  Mock.esp_err_to_name_r_CallInstance = CMock_Guts_MemNext(Mock.esp_err_to_name_r_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_esp_err_to_name_r,CMockString_code);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_code), (void*)(&code), sizeof(esp_err_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_esp_err_to_name_r,CMockString_buf);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_buf, buf, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_esp_err_to_name_r,CMockString_buflen);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_buflen), (void*)(&buflen), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_esp_err_to_name_r(CMOCK_esp_err_to_name_r_CALL_INSTANCE* cmock_call_instance, esp_err_t code, char* buf, size_t buflen);
void CMockExpectParameters_esp_err_to_name_r(CMOCK_esp_err_to_name_r_CALL_INSTANCE* cmock_call_instance, esp_err_t code, char* buf, size_t buflen)
{
  memcpy((void*)(&cmock_call_instance->Expected_code), (void*)(&code),
         sizeof(esp_err_t[sizeof(code) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_buf = buf;
  memcpy((void*)(&cmock_call_instance->Expected_buflen), (void*)(&buflen),
         sizeof(size_t[sizeof(buflen) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
}

void esp_err_to_name_r_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t code, char* buf, size_t buflen, const char* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_esp_err_to_name_r_CALL_INSTANCE));
  CMOCK_esp_err_to_name_r_CALL_INSTANCE* cmock_call_instance = (CMOCK_esp_err_to_name_r_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.esp_err_to_name_r_CallInstance = CMock_Guts_MemChain(Mock.esp_err_to_name_r_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_esp_err_to_name_r(cmock_call_instance, code, buf, buflen);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void _esp_error_check_failed(esp_err_t rc, const char* file, int line, const char* function, const char* expression)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK__esp_error_check_failed_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString__esp_error_check_failed);
  cmock_call_instance = (CMOCK__esp_error_check_failed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock._esp_error_check_failed_CallInstance);
  Mock._esp_error_check_failed_CallInstance = CMock_Guts_MemNext(Mock._esp_error_check_failed_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString__esp_error_check_failed,CMockString_rc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_rc), (void*)(&rc), sizeof(esp_err_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString__esp_error_check_failed,CMockString_file);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_file, file, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString__esp_error_check_failed,CMockString_line);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_line, line, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString__esp_error_check_failed,CMockString_function);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_function, function, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString__esp_error_check_failed,CMockString_expression);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_expression, expression, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters__esp_error_check_failed(CMOCK__esp_error_check_failed_CALL_INSTANCE* cmock_call_instance, esp_err_t rc, const char* file, int line, const char* function, const char* expression);
void CMockExpectParameters__esp_error_check_failed(CMOCK__esp_error_check_failed_CALL_INSTANCE* cmock_call_instance, esp_err_t rc, const char* file, int line, const char* function, const char* expression)
{
  memcpy((void*)(&cmock_call_instance->Expected_rc), (void*)(&rc),
         sizeof(esp_err_t[sizeof(rc) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_file = file;
  cmock_call_instance->Expected_line = line;
  cmock_call_instance->Expected_function = function;
  cmock_call_instance->Expected_expression = expression;
}

void _esp_error_check_failed_CMockExpect(UNITY_LINE_TYPE cmock_line, esp_err_t rc, const char* file, int line, const char* function, const char* expression)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK__esp_error_check_failed_CALL_INSTANCE));
  CMOCK__esp_error_check_failed_CALL_INSTANCE* cmock_call_instance = (CMOCK__esp_error_check_failed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock._esp_error_check_failed_CallInstance = CMock_Guts_MemChain(Mock._esp_error_check_failed_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters__esp_error_check_failed(cmock_call_instance, rc, file, line, function, expression);
}

void _esp_error_check_failed_without_abort(esp_err_t rc, const char* file, int line, const char* function, const char* expression)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK__esp_error_check_failed_without_abort_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString__esp_error_check_failed_without_abort);
  cmock_call_instance = (CMOCK__esp_error_check_failed_without_abort_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock._esp_error_check_failed_without_abort_CallInstance);
  Mock._esp_error_check_failed_without_abort_CallInstance = CMock_Guts_MemNext(Mock._esp_error_check_failed_without_abort_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString__esp_error_check_failed_without_abort,CMockString_rc);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_rc), (void*)(&rc), sizeof(esp_err_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString__esp_error_check_failed_without_abort,CMockString_file);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_file, file, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString__esp_error_check_failed_without_abort,CMockString_line);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_line, line, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString__esp_error_check_failed_without_abort,CMockString_function);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_function, function, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString__esp_error_check_failed_without_abort,CMockString_expression);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_expression, expression, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters__esp_error_check_failed_without_abort(CMOCK__esp_error_check_failed_without_abort_CALL_INSTANCE* cmock_call_instance, esp_err_t rc, const char* file, int line, const char* function, const char* expression);
void CMockExpectParameters__esp_error_check_failed_without_abort(CMOCK__esp_error_check_failed_without_abort_CALL_INSTANCE* cmock_call_instance, esp_err_t rc, const char* file, int line, const char* function, const char* expression)
{
  memcpy((void*)(&cmock_call_instance->Expected_rc), (void*)(&rc),
         sizeof(esp_err_t[sizeof(rc) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_file = file;
  cmock_call_instance->Expected_line = line;
  cmock_call_instance->Expected_function = function;
  cmock_call_instance->Expected_expression = expression;
}

void _esp_error_check_failed_without_abort_CMockExpect(UNITY_LINE_TYPE cmock_line, esp_err_t rc, const char* file, int line, const char* function, const char* expression)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK__esp_error_check_failed_without_abort_CALL_INSTANCE));
  CMOCK__esp_error_check_failed_without_abort_CALL_INSTANCE* cmock_call_instance = (CMOCK__esp_error_check_failed_without_abort_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock._esp_error_check_failed_without_abort_CallInstance = CMock_Guts_MemChain(Mock._esp_error_check_failed_without_abort_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters__esp_error_check_failed_without_abort(cmock_call_instance, rc, file, line, function, expression);
}

