/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKMAX7219_H
#define _MOCKMAX7219_H

#include "unity.h"
#include "max7219.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockmax7219_Init(void);
void Mockmax7219_Destroy(void);
void Mockmax7219_Verify(void);




#define max7219_init_desc_IgnoreAndReturn(cmock_retval) max7219_init_desc_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void max7219_init_desc_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define max7219_init_desc_StopIgnore() max7219_init_desc_CMockStopIgnore()
void max7219_init_desc_CMockStopIgnore(void);
#define max7219_init_desc_ExpectAndReturn(dev, host, clock_speed_hz, cs_pin, cmock_retval) max7219_init_desc_CMockExpectAndReturn(__LINE__, dev, host, clock_speed_hz, cs_pin, cmock_retval)
void max7219_init_desc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, spi_host_device_t host, uint32_t clock_speed_hz, gpio_num_t cs_pin, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_max7219_init_desc_CALLBACK)(max7219_t* dev, spi_host_device_t host, uint32_t clock_speed_hz, gpio_num_t cs_pin, int cmock_num_calls);
void max7219_init_desc_AddCallback(CMOCK_max7219_init_desc_CALLBACK Callback);
void max7219_init_desc_Stub(CMOCK_max7219_init_desc_CALLBACK Callback);
#define max7219_init_desc_StubWithCallback max7219_init_desc_Stub
#define max7219_init_desc_ExpectWithArrayAndReturn(dev, dev_Depth, host, clock_speed_hz, cs_pin, cmock_retval) max7219_init_desc_CMockExpectWithArrayAndReturn(__LINE__, dev, dev_Depth, host, clock_speed_hz, cs_pin, cmock_retval)
void max7219_init_desc_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, int dev_Depth, spi_host_device_t host, uint32_t clock_speed_hz, gpio_num_t cs_pin, esp_err_t cmock_to_return);
#define max7219_init_desc_ReturnThruPtr_dev(dev) max7219_init_desc_CMockReturnMemThruPtr_dev(__LINE__, dev, sizeof(max7219_t))
#define max7219_init_desc_ReturnArrayThruPtr_dev(dev, cmock_len) max7219_init_desc_CMockReturnMemThruPtr_dev(__LINE__, dev, cmock_len * sizeof(*dev))
#define max7219_init_desc_ReturnMemThruPtr_dev(dev, cmock_size) max7219_init_desc_CMockReturnMemThruPtr_dev(__LINE__, dev, cmock_size)
void max7219_init_desc_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, max7219_t const* dev, size_t cmock_size);
#define max7219_init_desc_IgnoreArg_dev() max7219_init_desc_CMockIgnoreArg_dev(__LINE__)
void max7219_init_desc_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line);
#define max7219_init_desc_IgnoreArg_host() max7219_init_desc_CMockIgnoreArg_host(__LINE__)
void max7219_init_desc_CMockIgnoreArg_host(UNITY_LINE_TYPE cmock_line);
#define max7219_init_desc_IgnoreArg_clock_speed_hz() max7219_init_desc_CMockIgnoreArg_clock_speed_hz(__LINE__)
void max7219_init_desc_CMockIgnoreArg_clock_speed_hz(UNITY_LINE_TYPE cmock_line);
#define max7219_init_desc_IgnoreArg_cs_pin() max7219_init_desc_CMockIgnoreArg_cs_pin(__LINE__)
void max7219_init_desc_CMockIgnoreArg_cs_pin(UNITY_LINE_TYPE cmock_line);
#define max7219_free_desc_IgnoreAndReturn(cmock_retval) max7219_free_desc_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void max7219_free_desc_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define max7219_free_desc_StopIgnore() max7219_free_desc_CMockStopIgnore()
void max7219_free_desc_CMockStopIgnore(void);
#define max7219_free_desc_ExpectAndReturn(dev, cmock_retval) max7219_free_desc_CMockExpectAndReturn(__LINE__, dev, cmock_retval)
void max7219_free_desc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_max7219_free_desc_CALLBACK)(max7219_t* dev, int cmock_num_calls);
void max7219_free_desc_AddCallback(CMOCK_max7219_free_desc_CALLBACK Callback);
void max7219_free_desc_Stub(CMOCK_max7219_free_desc_CALLBACK Callback);
#define max7219_free_desc_StubWithCallback max7219_free_desc_Stub
#define max7219_free_desc_ExpectWithArrayAndReturn(dev, dev_Depth, cmock_retval) max7219_free_desc_CMockExpectWithArrayAndReturn(__LINE__, dev, dev_Depth, cmock_retval)
void max7219_free_desc_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, int dev_Depth, esp_err_t cmock_to_return);
#define max7219_free_desc_ReturnThruPtr_dev(dev) max7219_free_desc_CMockReturnMemThruPtr_dev(__LINE__, dev, sizeof(max7219_t))
#define max7219_free_desc_ReturnArrayThruPtr_dev(dev, cmock_len) max7219_free_desc_CMockReturnMemThruPtr_dev(__LINE__, dev, cmock_len * sizeof(*dev))
#define max7219_free_desc_ReturnMemThruPtr_dev(dev, cmock_size) max7219_free_desc_CMockReturnMemThruPtr_dev(__LINE__, dev, cmock_size)
void max7219_free_desc_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, max7219_t const* dev, size_t cmock_size);
#define max7219_free_desc_IgnoreArg_dev() max7219_free_desc_CMockIgnoreArg_dev(__LINE__)
void max7219_free_desc_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line);
#define max7219_init_IgnoreAndReturn(cmock_retval) max7219_init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void max7219_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define max7219_init_StopIgnore() max7219_init_CMockStopIgnore()
void max7219_init_CMockStopIgnore(void);
#define max7219_init_ExpectAndReturn(dev, cmock_retval) max7219_init_CMockExpectAndReturn(__LINE__, dev, cmock_retval)
void max7219_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_max7219_init_CALLBACK)(max7219_t* dev, int cmock_num_calls);
void max7219_init_AddCallback(CMOCK_max7219_init_CALLBACK Callback);
void max7219_init_Stub(CMOCK_max7219_init_CALLBACK Callback);
#define max7219_init_StubWithCallback max7219_init_Stub
#define max7219_init_ExpectWithArrayAndReturn(dev, dev_Depth, cmock_retval) max7219_init_CMockExpectWithArrayAndReturn(__LINE__, dev, dev_Depth, cmock_retval)
void max7219_init_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, int dev_Depth, esp_err_t cmock_to_return);
#define max7219_init_ReturnThruPtr_dev(dev) max7219_init_CMockReturnMemThruPtr_dev(__LINE__, dev, sizeof(max7219_t))
#define max7219_init_ReturnArrayThruPtr_dev(dev, cmock_len) max7219_init_CMockReturnMemThruPtr_dev(__LINE__, dev, cmock_len * sizeof(*dev))
#define max7219_init_ReturnMemThruPtr_dev(dev, cmock_size) max7219_init_CMockReturnMemThruPtr_dev(__LINE__, dev, cmock_size)
void max7219_init_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, max7219_t const* dev, size_t cmock_size);
#define max7219_init_IgnoreArg_dev() max7219_init_CMockIgnoreArg_dev(__LINE__)
void max7219_init_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line);
#define max7219_set_decode_mode_IgnoreAndReturn(cmock_retval) max7219_set_decode_mode_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void max7219_set_decode_mode_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define max7219_set_decode_mode_StopIgnore() max7219_set_decode_mode_CMockStopIgnore()
void max7219_set_decode_mode_CMockStopIgnore(void);
#define max7219_set_decode_mode_ExpectAndReturn(dev, bcd, cmock_retval) max7219_set_decode_mode_CMockExpectAndReturn(__LINE__, dev, bcd, cmock_retval)
void max7219_set_decode_mode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, bool bcd, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_max7219_set_decode_mode_CALLBACK)(max7219_t* dev, bool bcd, int cmock_num_calls);
void max7219_set_decode_mode_AddCallback(CMOCK_max7219_set_decode_mode_CALLBACK Callback);
void max7219_set_decode_mode_Stub(CMOCK_max7219_set_decode_mode_CALLBACK Callback);
#define max7219_set_decode_mode_StubWithCallback max7219_set_decode_mode_Stub
#define max7219_set_decode_mode_ExpectWithArrayAndReturn(dev, dev_Depth, bcd, cmock_retval) max7219_set_decode_mode_CMockExpectWithArrayAndReturn(__LINE__, dev, dev_Depth, bcd, cmock_retval)
void max7219_set_decode_mode_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, int dev_Depth, bool bcd, esp_err_t cmock_to_return);
#define max7219_set_decode_mode_ReturnThruPtr_dev(dev) max7219_set_decode_mode_CMockReturnMemThruPtr_dev(__LINE__, dev, sizeof(max7219_t))
#define max7219_set_decode_mode_ReturnArrayThruPtr_dev(dev, cmock_len) max7219_set_decode_mode_CMockReturnMemThruPtr_dev(__LINE__, dev, cmock_len * sizeof(*dev))
#define max7219_set_decode_mode_ReturnMemThruPtr_dev(dev, cmock_size) max7219_set_decode_mode_CMockReturnMemThruPtr_dev(__LINE__, dev, cmock_size)
void max7219_set_decode_mode_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, max7219_t const* dev, size_t cmock_size);
#define max7219_set_decode_mode_IgnoreArg_dev() max7219_set_decode_mode_CMockIgnoreArg_dev(__LINE__)
void max7219_set_decode_mode_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line);
#define max7219_set_decode_mode_IgnoreArg_bcd() max7219_set_decode_mode_CMockIgnoreArg_bcd(__LINE__)
void max7219_set_decode_mode_CMockIgnoreArg_bcd(UNITY_LINE_TYPE cmock_line);
#define max7219_set_brightness_IgnoreAndReturn(cmock_retval) max7219_set_brightness_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void max7219_set_brightness_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define max7219_set_brightness_StopIgnore() max7219_set_brightness_CMockStopIgnore()
void max7219_set_brightness_CMockStopIgnore(void);
#define max7219_set_brightness_ExpectAndReturn(dev, value, cmock_retval) max7219_set_brightness_CMockExpectAndReturn(__LINE__, dev, value, cmock_retval)
void max7219_set_brightness_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, uint8_t value, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_max7219_set_brightness_CALLBACK)(max7219_t* dev, uint8_t value, int cmock_num_calls);
void max7219_set_brightness_AddCallback(CMOCK_max7219_set_brightness_CALLBACK Callback);
void max7219_set_brightness_Stub(CMOCK_max7219_set_brightness_CALLBACK Callback);
#define max7219_set_brightness_StubWithCallback max7219_set_brightness_Stub
#define max7219_set_brightness_ExpectWithArrayAndReturn(dev, dev_Depth, value, cmock_retval) max7219_set_brightness_CMockExpectWithArrayAndReturn(__LINE__, dev, dev_Depth, value, cmock_retval)
void max7219_set_brightness_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, int dev_Depth, uint8_t value, esp_err_t cmock_to_return);
#define max7219_set_brightness_ReturnThruPtr_dev(dev) max7219_set_brightness_CMockReturnMemThruPtr_dev(__LINE__, dev, sizeof(max7219_t))
#define max7219_set_brightness_ReturnArrayThruPtr_dev(dev, cmock_len) max7219_set_brightness_CMockReturnMemThruPtr_dev(__LINE__, dev, cmock_len * sizeof(*dev))
#define max7219_set_brightness_ReturnMemThruPtr_dev(dev, cmock_size) max7219_set_brightness_CMockReturnMemThruPtr_dev(__LINE__, dev, cmock_size)
void max7219_set_brightness_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, max7219_t const* dev, size_t cmock_size);
#define max7219_set_brightness_IgnoreArg_dev() max7219_set_brightness_CMockIgnoreArg_dev(__LINE__)
void max7219_set_brightness_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line);
#define max7219_set_brightness_IgnoreArg_value() max7219_set_brightness_CMockIgnoreArg_value(__LINE__)
void max7219_set_brightness_CMockIgnoreArg_value(UNITY_LINE_TYPE cmock_line);
#define max7219_set_shutdown_mode_IgnoreAndReturn(cmock_retval) max7219_set_shutdown_mode_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void max7219_set_shutdown_mode_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define max7219_set_shutdown_mode_StopIgnore() max7219_set_shutdown_mode_CMockStopIgnore()
void max7219_set_shutdown_mode_CMockStopIgnore(void);
#define max7219_set_shutdown_mode_ExpectAndReturn(dev, shutdown, cmock_retval) max7219_set_shutdown_mode_CMockExpectAndReturn(__LINE__, dev, shutdown, cmock_retval)
void max7219_set_shutdown_mode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, bool shutdown, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_max7219_set_shutdown_mode_CALLBACK)(max7219_t* dev, bool shutdown, int cmock_num_calls);
void max7219_set_shutdown_mode_AddCallback(CMOCK_max7219_set_shutdown_mode_CALLBACK Callback);
void max7219_set_shutdown_mode_Stub(CMOCK_max7219_set_shutdown_mode_CALLBACK Callback);
#define max7219_set_shutdown_mode_StubWithCallback max7219_set_shutdown_mode_Stub
#define max7219_set_shutdown_mode_ExpectWithArrayAndReturn(dev, dev_Depth, shutdown, cmock_retval) max7219_set_shutdown_mode_CMockExpectWithArrayAndReturn(__LINE__, dev, dev_Depth, shutdown, cmock_retval)
void max7219_set_shutdown_mode_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, int dev_Depth, bool shutdown, esp_err_t cmock_to_return);
#define max7219_set_shutdown_mode_ReturnThruPtr_dev(dev) max7219_set_shutdown_mode_CMockReturnMemThruPtr_dev(__LINE__, dev, sizeof(max7219_t))
#define max7219_set_shutdown_mode_ReturnArrayThruPtr_dev(dev, cmock_len) max7219_set_shutdown_mode_CMockReturnMemThruPtr_dev(__LINE__, dev, cmock_len * sizeof(*dev))
#define max7219_set_shutdown_mode_ReturnMemThruPtr_dev(dev, cmock_size) max7219_set_shutdown_mode_CMockReturnMemThruPtr_dev(__LINE__, dev, cmock_size)
void max7219_set_shutdown_mode_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, max7219_t const* dev, size_t cmock_size);
#define max7219_set_shutdown_mode_IgnoreArg_dev() max7219_set_shutdown_mode_CMockIgnoreArg_dev(__LINE__)
void max7219_set_shutdown_mode_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line);
#define max7219_set_shutdown_mode_IgnoreArg_shutdown() max7219_set_shutdown_mode_CMockIgnoreArg_shutdown(__LINE__)
void max7219_set_shutdown_mode_CMockIgnoreArg_shutdown(UNITY_LINE_TYPE cmock_line);
#define max7219_set_digit_IgnoreAndReturn(cmock_retval) max7219_set_digit_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void max7219_set_digit_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define max7219_set_digit_StopIgnore() max7219_set_digit_CMockStopIgnore()
void max7219_set_digit_CMockStopIgnore(void);
#define max7219_set_digit_ExpectAndReturn(dev, digit, val, cmock_retval) max7219_set_digit_CMockExpectAndReturn(__LINE__, dev, digit, val, cmock_retval)
void max7219_set_digit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, uint8_t digit, uint8_t val, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_max7219_set_digit_CALLBACK)(max7219_t* dev, uint8_t digit, uint8_t val, int cmock_num_calls);
void max7219_set_digit_AddCallback(CMOCK_max7219_set_digit_CALLBACK Callback);
void max7219_set_digit_Stub(CMOCK_max7219_set_digit_CALLBACK Callback);
#define max7219_set_digit_StubWithCallback max7219_set_digit_Stub
#define max7219_set_digit_ExpectWithArrayAndReturn(dev, dev_Depth, digit, val, cmock_retval) max7219_set_digit_CMockExpectWithArrayAndReturn(__LINE__, dev, dev_Depth, digit, val, cmock_retval)
void max7219_set_digit_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, int dev_Depth, uint8_t digit, uint8_t val, esp_err_t cmock_to_return);
#define max7219_set_digit_ReturnThruPtr_dev(dev) max7219_set_digit_CMockReturnMemThruPtr_dev(__LINE__, dev, sizeof(max7219_t))
#define max7219_set_digit_ReturnArrayThruPtr_dev(dev, cmock_len) max7219_set_digit_CMockReturnMemThruPtr_dev(__LINE__, dev, cmock_len * sizeof(*dev))
#define max7219_set_digit_ReturnMemThruPtr_dev(dev, cmock_size) max7219_set_digit_CMockReturnMemThruPtr_dev(__LINE__, dev, cmock_size)
void max7219_set_digit_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, max7219_t const* dev, size_t cmock_size);
#define max7219_set_digit_IgnoreArg_dev() max7219_set_digit_CMockIgnoreArg_dev(__LINE__)
void max7219_set_digit_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line);
#define max7219_set_digit_IgnoreArg_digit() max7219_set_digit_CMockIgnoreArg_digit(__LINE__)
void max7219_set_digit_CMockIgnoreArg_digit(UNITY_LINE_TYPE cmock_line);
#define max7219_set_digit_IgnoreArg_val() max7219_set_digit_CMockIgnoreArg_val(__LINE__)
void max7219_set_digit_CMockIgnoreArg_val(UNITY_LINE_TYPE cmock_line);
#define max7219_clear_IgnoreAndReturn(cmock_retval) max7219_clear_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void max7219_clear_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return);
#define max7219_clear_StopIgnore() max7219_clear_CMockStopIgnore()
void max7219_clear_CMockStopIgnore(void);
#define max7219_clear_ExpectAndReturn(dev, cmock_retval) max7219_clear_CMockExpectAndReturn(__LINE__, dev, cmock_retval)
void max7219_clear_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, esp_err_t cmock_to_return);
typedef esp_err_t (* CMOCK_max7219_clear_CALLBACK)(max7219_t* dev, int cmock_num_calls);
void max7219_clear_AddCallback(CMOCK_max7219_clear_CALLBACK Callback);
void max7219_clear_Stub(CMOCK_max7219_clear_CALLBACK Callback);
#define max7219_clear_StubWithCallback max7219_clear_Stub
#define max7219_clear_ExpectWithArrayAndReturn(dev, dev_Depth, cmock_retval) max7219_clear_CMockExpectWithArrayAndReturn(__LINE__, dev, dev_Depth, cmock_retval)
void max7219_clear_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, int dev_Depth, esp_err_t cmock_to_return);
#define max7219_clear_ReturnThruPtr_dev(dev) max7219_clear_CMockReturnMemThruPtr_dev(__LINE__, dev, sizeof(max7219_t))
#define max7219_clear_ReturnArrayThruPtr_dev(dev, cmock_len) max7219_clear_CMockReturnMemThruPtr_dev(__LINE__, dev, cmock_len * sizeof(*dev))
#define max7219_clear_ReturnMemThruPtr_dev(dev, cmock_size) max7219_clear_CMockReturnMemThruPtr_dev(__LINE__, dev, cmock_size)
void max7219_clear_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, max7219_t const* dev, size_t cmock_size);
#define max7219_clear_IgnoreArg_dev() max7219_clear_CMockIgnoreArg_dev(__LINE__)
void max7219_clear_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
