/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmatrix.h"

static const char* CMockString_center = "center";
static const char* CMockString_chr = "chr";
static const char* CMockString_copyText = "copyText";
static const char* CMockString_dev = "dev";
static const char* CMockString_getSpecialCharInfo = "getSpecialCharInfo";
static const char* CMockString_printBuffer = "printBuffer";
static const char* CMockString_scrollBuffer = "scrollBuffer";
static const char* CMockString_text = "text";
static const char* CMockString_textLength = "textLength";

typedef struct _CMOCK_copyText_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  max7219_t* Expected_dev;
  const char* Expected_text;
  bool Expected_center;

} CMOCK_copyText_CALL_INSTANCE;

typedef struct _CMOCK_scrollBuffer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  max7219_t* Expected_dev;

} CMOCK_scrollBuffer_CALL_INSTANCE;

typedef struct _CMOCK_printBuffer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  max7219_t* Expected_dev;

} CMOCK_printBuffer_CALL_INSTANCE;

typedef struct _CMOCK_textLength_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int ReturnVal;
  max7219_t* Expected_dev;
  const char* Expected_text;

} CMOCK_textLength_CALL_INSTANCE;

typedef struct _CMOCK_getSpecialCharInfo_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  SpecialCharInfo ReturnVal;
  uint8_t Expected_chr;

} CMOCK_getSpecialCharInfo_CALL_INSTANCE;

static struct MockmatrixInstance
{
  CMOCK_MEM_INDEX_TYPE copyText_CallInstance;
  CMOCK_MEM_INDEX_TYPE scrollBuffer_CallInstance;
  CMOCK_MEM_INDEX_TYPE printBuffer_CallInstance;
  CMOCK_MEM_INDEX_TYPE textLength_CallInstance;
  CMOCK_MEM_INDEX_TYPE getSpecialCharInfo_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmatrix_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.copyText_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_copyText);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.scrollBuffer_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_scrollBuffer);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.printBuffer_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_printBuffer);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.textLength_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_textLength);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.getSpecialCharInfo_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_getSpecialCharInfo);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void Mockmatrix_Init(void)
{
  Mockmatrix_Destroy();
}

void Mockmatrix_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void copyText(max7219_t* dev, const char* text, bool center)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_copyText_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_copyText);
  cmock_call_instance = (CMOCK_copyText_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.copyText_CallInstance);
  Mock.copyText_CallInstance = CMock_Guts_MemNext(Mock.copyText_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_copyText,CMockString_dev);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_dev), (void*)(dev), sizeof(max7219_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_copyText,CMockString_text);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_text, text, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_copyText,CMockString_center);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_center, center, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_copyText(CMOCK_copyText_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, const char* text, bool center);
void CMockExpectParameters_copyText(CMOCK_copyText_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, const char* text, bool center)
{
  cmock_call_instance->Expected_dev = dev;
  cmock_call_instance->Expected_text = text;
  cmock_call_instance->Expected_center = center;
}

void copyText_CMockExpect(UNITY_LINE_TYPE cmock_line, max7219_t* dev, const char* text, bool center)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_copyText_CALL_INSTANCE));
  CMOCK_copyText_CALL_INSTANCE* cmock_call_instance = (CMOCK_copyText_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.copyText_CallInstance = CMock_Guts_MemChain(Mock.copyText_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_copyText(cmock_call_instance, dev, text, center);
}

bool scrollBuffer(max7219_t* dev)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_scrollBuffer_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_scrollBuffer);
  cmock_call_instance = (CMOCK_scrollBuffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.scrollBuffer_CallInstance);
  Mock.scrollBuffer_CallInstance = CMock_Guts_MemNext(Mock.scrollBuffer_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_scrollBuffer,CMockString_dev);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_dev), (void*)(dev), sizeof(max7219_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_scrollBuffer(CMOCK_scrollBuffer_CALL_INSTANCE* cmock_call_instance, max7219_t* dev);
void CMockExpectParameters_scrollBuffer(CMOCK_scrollBuffer_CALL_INSTANCE* cmock_call_instance, max7219_t* dev)
{
  cmock_call_instance->Expected_dev = dev;
}

void scrollBuffer_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_scrollBuffer_CALL_INSTANCE));
  CMOCK_scrollBuffer_CALL_INSTANCE* cmock_call_instance = (CMOCK_scrollBuffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.scrollBuffer_CallInstance = CMock_Guts_MemChain(Mock.scrollBuffer_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_scrollBuffer(cmock_call_instance, dev);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void printBuffer(max7219_t* dev)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_printBuffer_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_printBuffer);
  cmock_call_instance = (CMOCK_printBuffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.printBuffer_CallInstance);
  Mock.printBuffer_CallInstance = CMock_Guts_MemNext(Mock.printBuffer_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_printBuffer,CMockString_dev);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_dev), (void*)(dev), sizeof(max7219_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_printBuffer(CMOCK_printBuffer_CALL_INSTANCE* cmock_call_instance, max7219_t* dev);
void CMockExpectParameters_printBuffer(CMOCK_printBuffer_CALL_INSTANCE* cmock_call_instance, max7219_t* dev)
{
  cmock_call_instance->Expected_dev = dev;
}

void printBuffer_CMockExpect(UNITY_LINE_TYPE cmock_line, max7219_t* dev)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_printBuffer_CALL_INSTANCE));
  CMOCK_printBuffer_CALL_INSTANCE* cmock_call_instance = (CMOCK_printBuffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.printBuffer_CallInstance = CMock_Guts_MemChain(Mock.printBuffer_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_printBuffer(cmock_call_instance, dev);
}

int textLength(max7219_t* dev, const char* text)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_textLength_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_textLength);
  cmock_call_instance = (CMOCK_textLength_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.textLength_CallInstance);
  Mock.textLength_CallInstance = CMock_Guts_MemNext(Mock.textLength_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_textLength,CMockString_dev);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_dev), (void*)(dev), sizeof(max7219_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_textLength,CMockString_text);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_text, text, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_textLength(CMOCK_textLength_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, const char* text);
void CMockExpectParameters_textLength(CMOCK_textLength_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, const char* text)
{
  cmock_call_instance->Expected_dev = dev;
  cmock_call_instance->Expected_text = text;
}

void textLength_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, const char* text, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_textLength_CALL_INSTANCE));
  CMOCK_textLength_CALL_INSTANCE* cmock_call_instance = (CMOCK_textLength_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.textLength_CallInstance = CMock_Guts_MemChain(Mock.textLength_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_textLength(cmock_call_instance, dev, text);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

SpecialCharInfo getSpecialCharInfo(uint8_t chr)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_getSpecialCharInfo_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_getSpecialCharInfo);
  cmock_call_instance = (CMOCK_getSpecialCharInfo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.getSpecialCharInfo_CallInstance);
  Mock.getSpecialCharInfo_CallInstance = CMock_Guts_MemNext(Mock.getSpecialCharInfo_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_getSpecialCharInfo,CMockString_chr);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_chr, chr, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_getSpecialCharInfo(CMOCK_getSpecialCharInfo_CALL_INSTANCE* cmock_call_instance, uint8_t chr);
void CMockExpectParameters_getSpecialCharInfo(CMOCK_getSpecialCharInfo_CALL_INSTANCE* cmock_call_instance, uint8_t chr)
{
  cmock_call_instance->Expected_chr = chr;
}

void getSpecialCharInfo_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t chr, SpecialCharInfo cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_getSpecialCharInfo_CALL_INSTANCE));
  CMOCK_getSpecialCharInfo_CALL_INSTANCE* cmock_call_instance = (CMOCK_getSpecialCharInfo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.getSpecialCharInfo_CallInstance = CMock_Guts_MemChain(Mock.getSpecialCharInfo_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_getSpecialCharInfo(cmock_call_instance, chr);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(SpecialCharInfo[sizeof(cmock_to_return) == sizeof(SpecialCharInfo) ? 1 : -1])); /* add SpecialCharInfo to :treat_as_array if this causes an error */
}

