/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKMATRIX_H
#define _MOCKMATRIX_H

#include "unity.h"
#include "matrix.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void Mockmatrix_Init(void);
void Mockmatrix_Destroy(void);
void Mockmatrix_Verify(void);




#define copyText_Expect(dev, text, center) copyText_CMockExpect(__LINE__, dev, text, center)
void copyText_CMockExpect(UNITY_LINE_TYPE cmock_line, max7219_t* dev, const char* text, bool center);
#define scrollBuffer_ExpectAndReturn(dev, cmock_retval) scrollBuffer_CMockExpectAndReturn(__LINE__, dev, cmock_retval)
void scrollBuffer_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, bool cmock_to_return);
#define printBuffer_Expect(dev) printBuffer_CMockExpect(__LINE__, dev)
void printBuffer_CMockExpect(UNITY_LINE_TYPE cmock_line, max7219_t* dev);
#define textLength_ExpectAndReturn(dev, text, cmock_retval) textLength_CMockExpectAndReturn(__LINE__, dev, text, cmock_retval)
void textLength_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, const char* text, int cmock_to_return);
#define getSpecialCharInfo_ExpectAndReturn(chr, cmock_retval) getSpecialCharInfo_CMockExpectAndReturn(__LINE__, chr, cmock_retval)
void getSpecialCharInfo_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t chr, SpecialCharInfo cmock_to_return);

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
