/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmax7219.h"

static const char* CMockString_bcd = "bcd";
static const char* CMockString_clock_speed_hz = "clock_speed_hz";
static const char* CMockString_cs_pin = "cs_pin";
static const char* CMockString_dev = "dev";
static const char* CMockString_digit = "digit";
static const char* CMockString_host = "host";
static const char* CMockString_max7219_clear = "max7219_clear";
static const char* CMockString_max7219_free_desc = "max7219_free_desc";
static const char* CMockString_max7219_init = "max7219_init";
static const char* CMockString_max7219_init_desc = "max7219_init_desc";
static const char* CMockString_max7219_set_brightness = "max7219_set_brightness";
static const char* CMockString_max7219_set_decode_mode = "max7219_set_decode_mode";
static const char* CMockString_max7219_set_digit = "max7219_set_digit";
static const char* CMockString_max7219_set_shutdown_mode = "max7219_set_shutdown_mode";
static const char* CMockString_shutdown = "shutdown";
static const char* CMockString_val = "val";
static const char* CMockString_value = "value";

typedef struct _CMOCK_max7219_init_desc_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  max7219_t* Expected_dev;
  spi_host_device_t Expected_host;
  uint32_t Expected_clock_speed_hz;
  gpio_num_t Expected_cs_pin;
  int Expected_dev_Depth;
  char ReturnThruPtr_dev_Used;
  max7219_t const* ReturnThruPtr_dev_Val;
  size_t ReturnThruPtr_dev_Size;
  char IgnoreArg_dev;
  char IgnoreArg_host;
  char IgnoreArg_clock_speed_hz;
  char IgnoreArg_cs_pin;

} CMOCK_max7219_init_desc_CALL_INSTANCE;

typedef struct _CMOCK_max7219_free_desc_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  max7219_t* Expected_dev;
  int Expected_dev_Depth;
  char ReturnThruPtr_dev_Used;
  max7219_t const* ReturnThruPtr_dev_Val;
  size_t ReturnThruPtr_dev_Size;
  char IgnoreArg_dev;

} CMOCK_max7219_free_desc_CALL_INSTANCE;

typedef struct _CMOCK_max7219_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  max7219_t* Expected_dev;
  int Expected_dev_Depth;
  char ReturnThruPtr_dev_Used;
  max7219_t const* ReturnThruPtr_dev_Val;
  size_t ReturnThruPtr_dev_Size;
  char IgnoreArg_dev;

} CMOCK_max7219_init_CALL_INSTANCE;

typedef struct _CMOCK_max7219_set_decode_mode_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  max7219_t* Expected_dev;
  bool Expected_bcd;
  int Expected_dev_Depth;
  char ReturnThruPtr_dev_Used;
  max7219_t const* ReturnThruPtr_dev_Val;
  size_t ReturnThruPtr_dev_Size;
  char IgnoreArg_dev;
  char IgnoreArg_bcd;

} CMOCK_max7219_set_decode_mode_CALL_INSTANCE;

typedef struct _CMOCK_max7219_set_brightness_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  max7219_t* Expected_dev;
  uint8_t Expected_value;
  int Expected_dev_Depth;
  char ReturnThruPtr_dev_Used;
  max7219_t const* ReturnThruPtr_dev_Val;
  size_t ReturnThruPtr_dev_Size;
  char IgnoreArg_dev;
  char IgnoreArg_value;

} CMOCK_max7219_set_brightness_CALL_INSTANCE;

typedef struct _CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  max7219_t* Expected_dev;
  bool Expected_shutdown;
  int Expected_dev_Depth;
  char ReturnThruPtr_dev_Used;
  max7219_t const* ReturnThruPtr_dev_Val;
  size_t ReturnThruPtr_dev_Size;
  char IgnoreArg_dev;
  char IgnoreArg_shutdown;

} CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE;

typedef struct _CMOCK_max7219_set_digit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  max7219_t* Expected_dev;
  uint8_t Expected_digit;
  uint8_t Expected_val;
  int Expected_dev_Depth;
  char ReturnThruPtr_dev_Used;
  max7219_t const* ReturnThruPtr_dev_Val;
  size_t ReturnThruPtr_dev_Size;
  char IgnoreArg_dev;
  char IgnoreArg_digit;
  char IgnoreArg_val;

} CMOCK_max7219_set_digit_CALL_INSTANCE;

typedef struct _CMOCK_max7219_clear_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  esp_err_t ReturnVal;
  max7219_t* Expected_dev;
  int Expected_dev_Depth;
  char ReturnThruPtr_dev_Used;
  max7219_t const* ReturnThruPtr_dev_Val;
  size_t ReturnThruPtr_dev_Size;
  char IgnoreArg_dev;

} CMOCK_max7219_clear_CALL_INSTANCE;

static struct Mockmax7219Instance
{
  char max7219_init_desc_IgnoreBool;
  esp_err_t max7219_init_desc_FinalReturn;
  char max7219_init_desc_CallbackBool;
  CMOCK_max7219_init_desc_CALLBACK max7219_init_desc_CallbackFunctionPointer;
  int max7219_init_desc_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE max7219_init_desc_CallInstance;
  char max7219_free_desc_IgnoreBool;
  esp_err_t max7219_free_desc_FinalReturn;
  char max7219_free_desc_CallbackBool;
  CMOCK_max7219_free_desc_CALLBACK max7219_free_desc_CallbackFunctionPointer;
  int max7219_free_desc_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE max7219_free_desc_CallInstance;
  char max7219_init_IgnoreBool;
  esp_err_t max7219_init_FinalReturn;
  char max7219_init_CallbackBool;
  CMOCK_max7219_init_CALLBACK max7219_init_CallbackFunctionPointer;
  int max7219_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE max7219_init_CallInstance;
  char max7219_set_decode_mode_IgnoreBool;
  esp_err_t max7219_set_decode_mode_FinalReturn;
  char max7219_set_decode_mode_CallbackBool;
  CMOCK_max7219_set_decode_mode_CALLBACK max7219_set_decode_mode_CallbackFunctionPointer;
  int max7219_set_decode_mode_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE max7219_set_decode_mode_CallInstance;
  char max7219_set_brightness_IgnoreBool;
  esp_err_t max7219_set_brightness_FinalReturn;
  char max7219_set_brightness_CallbackBool;
  CMOCK_max7219_set_brightness_CALLBACK max7219_set_brightness_CallbackFunctionPointer;
  int max7219_set_brightness_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE max7219_set_brightness_CallInstance;
  char max7219_set_shutdown_mode_IgnoreBool;
  esp_err_t max7219_set_shutdown_mode_FinalReturn;
  char max7219_set_shutdown_mode_CallbackBool;
  CMOCK_max7219_set_shutdown_mode_CALLBACK max7219_set_shutdown_mode_CallbackFunctionPointer;
  int max7219_set_shutdown_mode_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE max7219_set_shutdown_mode_CallInstance;
  char max7219_set_digit_IgnoreBool;
  esp_err_t max7219_set_digit_FinalReturn;
  char max7219_set_digit_CallbackBool;
  CMOCK_max7219_set_digit_CALLBACK max7219_set_digit_CallbackFunctionPointer;
  int max7219_set_digit_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE max7219_set_digit_CallInstance;
  char max7219_clear_IgnoreBool;
  esp_err_t max7219_clear_FinalReturn;
  char max7219_clear_CallbackBool;
  CMOCK_max7219_clear_CALLBACK max7219_clear_CallbackFunctionPointer;
  int max7219_clear_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE max7219_clear_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmax7219_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.max7219_init_desc_CallInstance;
  if (Mock.max7219_init_desc_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_max7219_init_desc);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.max7219_init_desc_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.max7219_free_desc_CallInstance;
  if (Mock.max7219_free_desc_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_max7219_free_desc);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.max7219_free_desc_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.max7219_init_CallInstance;
  if (Mock.max7219_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_max7219_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.max7219_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.max7219_set_decode_mode_CallInstance;
  if (Mock.max7219_set_decode_mode_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_max7219_set_decode_mode);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.max7219_set_decode_mode_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.max7219_set_brightness_CallInstance;
  if (Mock.max7219_set_brightness_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_max7219_set_brightness);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.max7219_set_brightness_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.max7219_set_shutdown_mode_CallInstance;
  if (Mock.max7219_set_shutdown_mode_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_max7219_set_shutdown_mode);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.max7219_set_shutdown_mode_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.max7219_set_digit_CallInstance;
  if (Mock.max7219_set_digit_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_max7219_set_digit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.max7219_set_digit_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.max7219_clear_CallInstance;
  if (Mock.max7219_clear_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_max7219_clear);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.max7219_clear_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockmax7219_Init(void)
{
  Mockmax7219_Destroy();
}

void Mockmax7219_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

esp_err_t max7219_init_desc(max7219_t* dev, spi_host_device_t host, uint32_t clock_speed_hz, gpio_num_t cs_pin)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_max7219_init_desc_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_max7219_init_desc);
  cmock_call_instance = (CMOCK_max7219_init_desc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.max7219_init_desc_CallInstance);
  Mock.max7219_init_desc_CallInstance = CMock_Guts_MemNext(Mock.max7219_init_desc_CallInstance);
  if (Mock.max7219_init_desc_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.max7219_init_desc_FinalReturn;
    memcpy((void*)(&Mock.max7219_init_desc_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.max7219_init_desc_CallbackBool &&
      Mock.max7219_init_desc_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.max7219_init_desc_CallbackFunctionPointer(dev, host, clock_speed_hz, cs_pin, Mock.max7219_init_desc_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_dev)
  {
    UNITY_SET_DETAILS(CMockString_max7219_init_desc,CMockString_dev);
    if (cmock_call_instance->Expected_dev == NULL)
      { UNITY_TEST_ASSERT_NULL(dev, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_dev), (void*)(dev), sizeof(max7219_t), cmock_call_instance->Expected_dev_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_host)
  {
    UNITY_SET_DETAILS(CMockString_max7219_init_desc,CMockString_host);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_host), (void*)(&host), sizeof(spi_host_device_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_clock_speed_hz)
  {
    UNITY_SET_DETAILS(CMockString_max7219_init_desc,CMockString_clock_speed_hz);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_clock_speed_hz, clock_speed_hz, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_cs_pin)
  {
    UNITY_SET_DETAILS(CMockString_max7219_init_desc,CMockString_cs_pin);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cs_pin), (void*)(&cs_pin), sizeof(gpio_num_t), cmock_line, CMockStringMismatch);
  }
  if (Mock.max7219_init_desc_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.max7219_init_desc_CallbackFunctionPointer(dev, host, clock_speed_hz, cs_pin, Mock.max7219_init_desc_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_dev_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(dev, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)dev, (const void*)cmock_call_instance->ReturnThruPtr_dev_Val,
      cmock_call_instance->ReturnThruPtr_dev_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_max7219_init_desc(CMOCK_max7219_init_desc_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, int dev_Depth, spi_host_device_t host, uint32_t clock_speed_hz, gpio_num_t cs_pin);
void CMockExpectParameters_max7219_init_desc(CMOCK_max7219_init_desc_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, int dev_Depth, spi_host_device_t host, uint32_t clock_speed_hz, gpio_num_t cs_pin)
{
  cmock_call_instance->Expected_dev = dev;
  cmock_call_instance->Expected_dev_Depth = dev_Depth;
  cmock_call_instance->IgnoreArg_dev = 0;
  cmock_call_instance->ReturnThruPtr_dev_Used = 0;
  memcpy((void*)(&cmock_call_instance->Expected_host), (void*)(&host),
         sizeof(spi_host_device_t[sizeof(host) == sizeof(spi_host_device_t) ? 1 : -1])); /* add spi_host_device_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_host = 0;
  cmock_call_instance->Expected_clock_speed_hz = clock_speed_hz;
  cmock_call_instance->IgnoreArg_clock_speed_hz = 0;
  memcpy((void*)(&cmock_call_instance->Expected_cs_pin), (void*)(&cs_pin),
         sizeof(gpio_num_t[sizeof(cs_pin) == sizeof(gpio_num_t) ? 1 : -1])); /* add gpio_num_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_cs_pin = 0;
}

void max7219_init_desc_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_init_desc_CALL_INSTANCE));
  CMOCK_max7219_init_desc_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_init_desc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_init_desc_CallInstance = CMock_Guts_MemChain(Mock.max7219_init_desc_CallInstance, cmock_guts_index);
  Mock.max7219_init_desc_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.max7219_init_desc_IgnoreBool = (char)1;
}

void max7219_init_desc_CMockStopIgnore(void)
{
  if(Mock.max7219_init_desc_IgnoreBool)
    Mock.max7219_init_desc_CallInstance = CMock_Guts_MemNext(Mock.max7219_init_desc_CallInstance);
  Mock.max7219_init_desc_IgnoreBool = (char)0;
}

void max7219_init_desc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, spi_host_device_t host, uint32_t clock_speed_hz, gpio_num_t cs_pin, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_init_desc_CALL_INSTANCE));
  CMOCK_max7219_init_desc_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_init_desc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_init_desc_CallInstance = CMock_Guts_MemChain(Mock.max7219_init_desc_CallInstance, cmock_guts_index);
  Mock.max7219_init_desc_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_max7219_init_desc(cmock_call_instance, dev, 1, host, clock_speed_hz, cs_pin);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void max7219_init_desc_AddCallback(CMOCK_max7219_init_desc_CALLBACK Callback)
{
  Mock.max7219_init_desc_IgnoreBool = (char)0;
  Mock.max7219_init_desc_CallbackBool = (char)1;
  Mock.max7219_init_desc_CallbackFunctionPointer = Callback;
}

void max7219_init_desc_Stub(CMOCK_max7219_init_desc_CALLBACK Callback)
{
  Mock.max7219_init_desc_IgnoreBool = (char)0;
  Mock.max7219_init_desc_CallbackBool = (char)0;
  Mock.max7219_init_desc_CallbackFunctionPointer = Callback;
}

void max7219_init_desc_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, int dev_Depth, spi_host_device_t host, uint32_t clock_speed_hz, gpio_num_t cs_pin, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_init_desc_CALL_INSTANCE));
  CMOCK_max7219_init_desc_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_init_desc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_init_desc_CallInstance = CMock_Guts_MemChain(Mock.max7219_init_desc_CallInstance, cmock_guts_index);
  Mock.max7219_init_desc_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_max7219_init_desc(cmock_call_instance, dev, dev_Depth, host, clock_speed_hz, cs_pin);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void max7219_init_desc_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, max7219_t const* dev, size_t cmock_size)
{
  CMOCK_max7219_init_desc_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_init_desc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_init_desc_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_dev_Used = 1;
  cmock_call_instance->ReturnThruPtr_dev_Val = dev;
  cmock_call_instance->ReturnThruPtr_dev_Size = cmock_size;
}

void max7219_init_desc_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_max7219_init_desc_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_init_desc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_init_desc_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dev = 1;
}

void max7219_init_desc_CMockIgnoreArg_host(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_max7219_init_desc_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_init_desc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_init_desc_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_host = 1;
}

void max7219_init_desc_CMockIgnoreArg_clock_speed_hz(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_max7219_init_desc_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_init_desc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_init_desc_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_clock_speed_hz = 1;
}

void max7219_init_desc_CMockIgnoreArg_cs_pin(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_max7219_init_desc_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_init_desc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_init_desc_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cs_pin = 1;
}

esp_err_t max7219_free_desc(max7219_t* dev)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_max7219_free_desc_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_max7219_free_desc);
  cmock_call_instance = (CMOCK_max7219_free_desc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.max7219_free_desc_CallInstance);
  Mock.max7219_free_desc_CallInstance = CMock_Guts_MemNext(Mock.max7219_free_desc_CallInstance);
  if (Mock.max7219_free_desc_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.max7219_free_desc_FinalReturn;
    memcpy((void*)(&Mock.max7219_free_desc_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.max7219_free_desc_CallbackBool &&
      Mock.max7219_free_desc_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.max7219_free_desc_CallbackFunctionPointer(dev, Mock.max7219_free_desc_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_dev)
  {
    UNITY_SET_DETAILS(CMockString_max7219_free_desc,CMockString_dev);
    if (cmock_call_instance->Expected_dev == NULL)
      { UNITY_TEST_ASSERT_NULL(dev, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_dev), (void*)(dev), sizeof(max7219_t), cmock_call_instance->Expected_dev_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.max7219_free_desc_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.max7219_free_desc_CallbackFunctionPointer(dev, Mock.max7219_free_desc_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_dev_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(dev, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)dev, (const void*)cmock_call_instance->ReturnThruPtr_dev_Val,
      cmock_call_instance->ReturnThruPtr_dev_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_max7219_free_desc(CMOCK_max7219_free_desc_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, int dev_Depth);
void CMockExpectParameters_max7219_free_desc(CMOCK_max7219_free_desc_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, int dev_Depth)
{
  cmock_call_instance->Expected_dev = dev;
  cmock_call_instance->Expected_dev_Depth = dev_Depth;
  cmock_call_instance->IgnoreArg_dev = 0;
  cmock_call_instance->ReturnThruPtr_dev_Used = 0;
}

void max7219_free_desc_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_free_desc_CALL_INSTANCE));
  CMOCK_max7219_free_desc_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_free_desc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_free_desc_CallInstance = CMock_Guts_MemChain(Mock.max7219_free_desc_CallInstance, cmock_guts_index);
  Mock.max7219_free_desc_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.max7219_free_desc_IgnoreBool = (char)1;
}

void max7219_free_desc_CMockStopIgnore(void)
{
  if(Mock.max7219_free_desc_IgnoreBool)
    Mock.max7219_free_desc_CallInstance = CMock_Guts_MemNext(Mock.max7219_free_desc_CallInstance);
  Mock.max7219_free_desc_IgnoreBool = (char)0;
}

void max7219_free_desc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_free_desc_CALL_INSTANCE));
  CMOCK_max7219_free_desc_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_free_desc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_free_desc_CallInstance = CMock_Guts_MemChain(Mock.max7219_free_desc_CallInstance, cmock_guts_index);
  Mock.max7219_free_desc_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_max7219_free_desc(cmock_call_instance, dev, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void max7219_free_desc_AddCallback(CMOCK_max7219_free_desc_CALLBACK Callback)
{
  Mock.max7219_free_desc_IgnoreBool = (char)0;
  Mock.max7219_free_desc_CallbackBool = (char)1;
  Mock.max7219_free_desc_CallbackFunctionPointer = Callback;
}

void max7219_free_desc_Stub(CMOCK_max7219_free_desc_CALLBACK Callback)
{
  Mock.max7219_free_desc_IgnoreBool = (char)0;
  Mock.max7219_free_desc_CallbackBool = (char)0;
  Mock.max7219_free_desc_CallbackFunctionPointer = Callback;
}

void max7219_free_desc_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, int dev_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_free_desc_CALL_INSTANCE));
  CMOCK_max7219_free_desc_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_free_desc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_free_desc_CallInstance = CMock_Guts_MemChain(Mock.max7219_free_desc_CallInstance, cmock_guts_index);
  Mock.max7219_free_desc_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_max7219_free_desc(cmock_call_instance, dev, dev_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void max7219_free_desc_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, max7219_t const* dev, size_t cmock_size)
{
  CMOCK_max7219_free_desc_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_free_desc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_free_desc_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_dev_Used = 1;
  cmock_call_instance->ReturnThruPtr_dev_Val = dev;
  cmock_call_instance->ReturnThruPtr_dev_Size = cmock_size;
}

void max7219_free_desc_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_max7219_free_desc_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_free_desc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_free_desc_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dev = 1;
}

esp_err_t max7219_init(max7219_t* dev)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_max7219_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_max7219_init);
  cmock_call_instance = (CMOCK_max7219_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.max7219_init_CallInstance);
  Mock.max7219_init_CallInstance = CMock_Guts_MemNext(Mock.max7219_init_CallInstance);
  if (Mock.max7219_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.max7219_init_FinalReturn;
    memcpy((void*)(&Mock.max7219_init_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.max7219_init_CallbackBool &&
      Mock.max7219_init_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.max7219_init_CallbackFunctionPointer(dev, Mock.max7219_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_dev)
  {
    UNITY_SET_DETAILS(CMockString_max7219_init,CMockString_dev);
    if (cmock_call_instance->Expected_dev == NULL)
      { UNITY_TEST_ASSERT_NULL(dev, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_dev), (void*)(dev), sizeof(max7219_t), cmock_call_instance->Expected_dev_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.max7219_init_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.max7219_init_CallbackFunctionPointer(dev, Mock.max7219_init_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_dev_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(dev, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)dev, (const void*)cmock_call_instance->ReturnThruPtr_dev_Val,
      cmock_call_instance->ReturnThruPtr_dev_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_max7219_init(CMOCK_max7219_init_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, int dev_Depth);
void CMockExpectParameters_max7219_init(CMOCK_max7219_init_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, int dev_Depth)
{
  cmock_call_instance->Expected_dev = dev;
  cmock_call_instance->Expected_dev_Depth = dev_Depth;
  cmock_call_instance->IgnoreArg_dev = 0;
  cmock_call_instance->ReturnThruPtr_dev_Used = 0;
}

void max7219_init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_init_CALL_INSTANCE));
  CMOCK_max7219_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_init_CallInstance = CMock_Guts_MemChain(Mock.max7219_init_CallInstance, cmock_guts_index);
  Mock.max7219_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.max7219_init_IgnoreBool = (char)1;
}

void max7219_init_CMockStopIgnore(void)
{
  if(Mock.max7219_init_IgnoreBool)
    Mock.max7219_init_CallInstance = CMock_Guts_MemNext(Mock.max7219_init_CallInstance);
  Mock.max7219_init_IgnoreBool = (char)0;
}

void max7219_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_init_CALL_INSTANCE));
  CMOCK_max7219_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_init_CallInstance = CMock_Guts_MemChain(Mock.max7219_init_CallInstance, cmock_guts_index);
  Mock.max7219_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_max7219_init(cmock_call_instance, dev, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void max7219_init_AddCallback(CMOCK_max7219_init_CALLBACK Callback)
{
  Mock.max7219_init_IgnoreBool = (char)0;
  Mock.max7219_init_CallbackBool = (char)1;
  Mock.max7219_init_CallbackFunctionPointer = Callback;
}

void max7219_init_Stub(CMOCK_max7219_init_CALLBACK Callback)
{
  Mock.max7219_init_IgnoreBool = (char)0;
  Mock.max7219_init_CallbackBool = (char)0;
  Mock.max7219_init_CallbackFunctionPointer = Callback;
}

void max7219_init_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, int dev_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_init_CALL_INSTANCE));
  CMOCK_max7219_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_init_CallInstance = CMock_Guts_MemChain(Mock.max7219_init_CallInstance, cmock_guts_index);
  Mock.max7219_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_max7219_init(cmock_call_instance, dev, dev_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void max7219_init_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, max7219_t const* dev, size_t cmock_size)
{
  CMOCK_max7219_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_dev_Used = 1;
  cmock_call_instance->ReturnThruPtr_dev_Val = dev;
  cmock_call_instance->ReturnThruPtr_dev_Size = cmock_size;
}

void max7219_init_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_max7219_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dev = 1;
}

esp_err_t max7219_set_decode_mode(max7219_t* dev, bool bcd)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_max7219_set_decode_mode_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_max7219_set_decode_mode);
  cmock_call_instance = (CMOCK_max7219_set_decode_mode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.max7219_set_decode_mode_CallInstance);
  Mock.max7219_set_decode_mode_CallInstance = CMock_Guts_MemNext(Mock.max7219_set_decode_mode_CallInstance);
  if (Mock.max7219_set_decode_mode_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.max7219_set_decode_mode_FinalReturn;
    memcpy((void*)(&Mock.max7219_set_decode_mode_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.max7219_set_decode_mode_CallbackBool &&
      Mock.max7219_set_decode_mode_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.max7219_set_decode_mode_CallbackFunctionPointer(dev, bcd, Mock.max7219_set_decode_mode_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_dev)
  {
    UNITY_SET_DETAILS(CMockString_max7219_set_decode_mode,CMockString_dev);
    if (cmock_call_instance->Expected_dev == NULL)
      { UNITY_TEST_ASSERT_NULL(dev, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_dev), (void*)(dev), sizeof(max7219_t), cmock_call_instance->Expected_dev_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_bcd)
  {
    UNITY_SET_DETAILS(CMockString_max7219_set_decode_mode,CMockString_bcd);
    UNITY_TEST_ASSERT_EQUAL_UINT8(cmock_call_instance->Expected_bcd, bcd, cmock_line, CMockStringMismatch);
  }
  if (Mock.max7219_set_decode_mode_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.max7219_set_decode_mode_CallbackFunctionPointer(dev, bcd, Mock.max7219_set_decode_mode_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_dev_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(dev, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)dev, (const void*)cmock_call_instance->ReturnThruPtr_dev_Val,
      cmock_call_instance->ReturnThruPtr_dev_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_max7219_set_decode_mode(CMOCK_max7219_set_decode_mode_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, int dev_Depth, bool bcd);
void CMockExpectParameters_max7219_set_decode_mode(CMOCK_max7219_set_decode_mode_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, int dev_Depth, bool bcd)
{
  cmock_call_instance->Expected_dev = dev;
  cmock_call_instance->Expected_dev_Depth = dev_Depth;
  cmock_call_instance->IgnoreArg_dev = 0;
  cmock_call_instance->ReturnThruPtr_dev_Used = 0;
  cmock_call_instance->Expected_bcd = bcd;
  cmock_call_instance->IgnoreArg_bcd = 0;
}

void max7219_set_decode_mode_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_set_decode_mode_CALL_INSTANCE));
  CMOCK_max7219_set_decode_mode_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_decode_mode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_set_decode_mode_CallInstance = CMock_Guts_MemChain(Mock.max7219_set_decode_mode_CallInstance, cmock_guts_index);
  Mock.max7219_set_decode_mode_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.max7219_set_decode_mode_IgnoreBool = (char)1;
}

void max7219_set_decode_mode_CMockStopIgnore(void)
{
  if(Mock.max7219_set_decode_mode_IgnoreBool)
    Mock.max7219_set_decode_mode_CallInstance = CMock_Guts_MemNext(Mock.max7219_set_decode_mode_CallInstance);
  Mock.max7219_set_decode_mode_IgnoreBool = (char)0;
}

void max7219_set_decode_mode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, bool bcd, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_set_decode_mode_CALL_INSTANCE));
  CMOCK_max7219_set_decode_mode_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_decode_mode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_set_decode_mode_CallInstance = CMock_Guts_MemChain(Mock.max7219_set_decode_mode_CallInstance, cmock_guts_index);
  Mock.max7219_set_decode_mode_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_max7219_set_decode_mode(cmock_call_instance, dev, 1, bcd);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void max7219_set_decode_mode_AddCallback(CMOCK_max7219_set_decode_mode_CALLBACK Callback)
{
  Mock.max7219_set_decode_mode_IgnoreBool = (char)0;
  Mock.max7219_set_decode_mode_CallbackBool = (char)1;
  Mock.max7219_set_decode_mode_CallbackFunctionPointer = Callback;
}

void max7219_set_decode_mode_Stub(CMOCK_max7219_set_decode_mode_CALLBACK Callback)
{
  Mock.max7219_set_decode_mode_IgnoreBool = (char)0;
  Mock.max7219_set_decode_mode_CallbackBool = (char)0;
  Mock.max7219_set_decode_mode_CallbackFunctionPointer = Callback;
}

void max7219_set_decode_mode_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, int dev_Depth, bool bcd, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_set_decode_mode_CALL_INSTANCE));
  CMOCK_max7219_set_decode_mode_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_decode_mode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_set_decode_mode_CallInstance = CMock_Guts_MemChain(Mock.max7219_set_decode_mode_CallInstance, cmock_guts_index);
  Mock.max7219_set_decode_mode_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_max7219_set_decode_mode(cmock_call_instance, dev, dev_Depth, bcd);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void max7219_set_decode_mode_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, max7219_t const* dev, size_t cmock_size)
{
  CMOCK_max7219_set_decode_mode_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_decode_mode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_set_decode_mode_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_dev_Used = 1;
  cmock_call_instance->ReturnThruPtr_dev_Val = dev;
  cmock_call_instance->ReturnThruPtr_dev_Size = cmock_size;
}

void max7219_set_decode_mode_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_max7219_set_decode_mode_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_decode_mode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_set_decode_mode_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dev = 1;
}

void max7219_set_decode_mode_CMockIgnoreArg_bcd(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_max7219_set_decode_mode_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_decode_mode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_set_decode_mode_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_bcd = 1;
}

esp_err_t max7219_set_brightness(max7219_t* dev, uint8_t value)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_max7219_set_brightness_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_max7219_set_brightness);
  cmock_call_instance = (CMOCK_max7219_set_brightness_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.max7219_set_brightness_CallInstance);
  Mock.max7219_set_brightness_CallInstance = CMock_Guts_MemNext(Mock.max7219_set_brightness_CallInstance);
  if (Mock.max7219_set_brightness_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.max7219_set_brightness_FinalReturn;
    memcpy((void*)(&Mock.max7219_set_brightness_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.max7219_set_brightness_CallbackBool &&
      Mock.max7219_set_brightness_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.max7219_set_brightness_CallbackFunctionPointer(dev, value, Mock.max7219_set_brightness_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_dev)
  {
    UNITY_SET_DETAILS(CMockString_max7219_set_brightness,CMockString_dev);
    if (cmock_call_instance->Expected_dev == NULL)
      { UNITY_TEST_ASSERT_NULL(dev, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_dev), (void*)(dev), sizeof(max7219_t), cmock_call_instance->Expected_dev_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_value)
  {
    UNITY_SET_DETAILS(CMockString_max7219_set_brightness,CMockString_value);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_value, value, cmock_line, CMockStringMismatch);
  }
  if (Mock.max7219_set_brightness_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.max7219_set_brightness_CallbackFunctionPointer(dev, value, Mock.max7219_set_brightness_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_dev_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(dev, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)dev, (const void*)cmock_call_instance->ReturnThruPtr_dev_Val,
      cmock_call_instance->ReturnThruPtr_dev_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_max7219_set_brightness(CMOCK_max7219_set_brightness_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, int dev_Depth, uint8_t value);
void CMockExpectParameters_max7219_set_brightness(CMOCK_max7219_set_brightness_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, int dev_Depth, uint8_t value)
{
  cmock_call_instance->Expected_dev = dev;
  cmock_call_instance->Expected_dev_Depth = dev_Depth;
  cmock_call_instance->IgnoreArg_dev = 0;
  cmock_call_instance->ReturnThruPtr_dev_Used = 0;
  cmock_call_instance->Expected_value = value;
  cmock_call_instance->IgnoreArg_value = 0;
}

void max7219_set_brightness_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_set_brightness_CALL_INSTANCE));
  CMOCK_max7219_set_brightness_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_brightness_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_set_brightness_CallInstance = CMock_Guts_MemChain(Mock.max7219_set_brightness_CallInstance, cmock_guts_index);
  Mock.max7219_set_brightness_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.max7219_set_brightness_IgnoreBool = (char)1;
}

void max7219_set_brightness_CMockStopIgnore(void)
{
  if(Mock.max7219_set_brightness_IgnoreBool)
    Mock.max7219_set_brightness_CallInstance = CMock_Guts_MemNext(Mock.max7219_set_brightness_CallInstance);
  Mock.max7219_set_brightness_IgnoreBool = (char)0;
}

void max7219_set_brightness_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, uint8_t value, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_set_brightness_CALL_INSTANCE));
  CMOCK_max7219_set_brightness_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_brightness_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_set_brightness_CallInstance = CMock_Guts_MemChain(Mock.max7219_set_brightness_CallInstance, cmock_guts_index);
  Mock.max7219_set_brightness_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_max7219_set_brightness(cmock_call_instance, dev, 1, value);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void max7219_set_brightness_AddCallback(CMOCK_max7219_set_brightness_CALLBACK Callback)
{
  Mock.max7219_set_brightness_IgnoreBool = (char)0;
  Mock.max7219_set_brightness_CallbackBool = (char)1;
  Mock.max7219_set_brightness_CallbackFunctionPointer = Callback;
}

void max7219_set_brightness_Stub(CMOCK_max7219_set_brightness_CALLBACK Callback)
{
  Mock.max7219_set_brightness_IgnoreBool = (char)0;
  Mock.max7219_set_brightness_CallbackBool = (char)0;
  Mock.max7219_set_brightness_CallbackFunctionPointer = Callback;
}

void max7219_set_brightness_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, int dev_Depth, uint8_t value, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_set_brightness_CALL_INSTANCE));
  CMOCK_max7219_set_brightness_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_brightness_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_set_brightness_CallInstance = CMock_Guts_MemChain(Mock.max7219_set_brightness_CallInstance, cmock_guts_index);
  Mock.max7219_set_brightness_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_max7219_set_brightness(cmock_call_instance, dev, dev_Depth, value);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void max7219_set_brightness_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, max7219_t const* dev, size_t cmock_size)
{
  CMOCK_max7219_set_brightness_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_brightness_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_set_brightness_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_dev_Used = 1;
  cmock_call_instance->ReturnThruPtr_dev_Val = dev;
  cmock_call_instance->ReturnThruPtr_dev_Size = cmock_size;
}

void max7219_set_brightness_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_max7219_set_brightness_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_brightness_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_set_brightness_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dev = 1;
}

void max7219_set_brightness_CMockIgnoreArg_value(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_max7219_set_brightness_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_brightness_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_set_brightness_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_value = 1;
}

esp_err_t max7219_set_shutdown_mode(max7219_t* dev, bool shutdown)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_max7219_set_shutdown_mode);
  cmock_call_instance = (CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.max7219_set_shutdown_mode_CallInstance);
  Mock.max7219_set_shutdown_mode_CallInstance = CMock_Guts_MemNext(Mock.max7219_set_shutdown_mode_CallInstance);
  if (Mock.max7219_set_shutdown_mode_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.max7219_set_shutdown_mode_FinalReturn;
    memcpy((void*)(&Mock.max7219_set_shutdown_mode_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.max7219_set_shutdown_mode_CallbackBool &&
      Mock.max7219_set_shutdown_mode_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.max7219_set_shutdown_mode_CallbackFunctionPointer(dev, shutdown, Mock.max7219_set_shutdown_mode_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_dev)
  {
    UNITY_SET_DETAILS(CMockString_max7219_set_shutdown_mode,CMockString_dev);
    if (cmock_call_instance->Expected_dev == NULL)
      { UNITY_TEST_ASSERT_NULL(dev, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_dev), (void*)(dev), sizeof(max7219_t), cmock_call_instance->Expected_dev_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_shutdown)
  {
    UNITY_SET_DETAILS(CMockString_max7219_set_shutdown_mode,CMockString_shutdown);
    UNITY_TEST_ASSERT_EQUAL_UINT8(cmock_call_instance->Expected_shutdown, shutdown, cmock_line, CMockStringMismatch);
  }
  if (Mock.max7219_set_shutdown_mode_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.max7219_set_shutdown_mode_CallbackFunctionPointer(dev, shutdown, Mock.max7219_set_shutdown_mode_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_dev_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(dev, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)dev, (const void*)cmock_call_instance->ReturnThruPtr_dev_Val,
      cmock_call_instance->ReturnThruPtr_dev_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_max7219_set_shutdown_mode(CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, int dev_Depth, bool shutdown);
void CMockExpectParameters_max7219_set_shutdown_mode(CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, int dev_Depth, bool shutdown)
{
  cmock_call_instance->Expected_dev = dev;
  cmock_call_instance->Expected_dev_Depth = dev_Depth;
  cmock_call_instance->IgnoreArg_dev = 0;
  cmock_call_instance->ReturnThruPtr_dev_Used = 0;
  cmock_call_instance->Expected_shutdown = shutdown;
  cmock_call_instance->IgnoreArg_shutdown = 0;
}

void max7219_set_shutdown_mode_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE));
  CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_set_shutdown_mode_CallInstance = CMock_Guts_MemChain(Mock.max7219_set_shutdown_mode_CallInstance, cmock_guts_index);
  Mock.max7219_set_shutdown_mode_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.max7219_set_shutdown_mode_IgnoreBool = (char)1;
}

void max7219_set_shutdown_mode_CMockStopIgnore(void)
{
  if(Mock.max7219_set_shutdown_mode_IgnoreBool)
    Mock.max7219_set_shutdown_mode_CallInstance = CMock_Guts_MemNext(Mock.max7219_set_shutdown_mode_CallInstance);
  Mock.max7219_set_shutdown_mode_IgnoreBool = (char)0;
}

void max7219_set_shutdown_mode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, bool shutdown, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE));
  CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_set_shutdown_mode_CallInstance = CMock_Guts_MemChain(Mock.max7219_set_shutdown_mode_CallInstance, cmock_guts_index);
  Mock.max7219_set_shutdown_mode_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_max7219_set_shutdown_mode(cmock_call_instance, dev, 1, shutdown);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void max7219_set_shutdown_mode_AddCallback(CMOCK_max7219_set_shutdown_mode_CALLBACK Callback)
{
  Mock.max7219_set_shutdown_mode_IgnoreBool = (char)0;
  Mock.max7219_set_shutdown_mode_CallbackBool = (char)1;
  Mock.max7219_set_shutdown_mode_CallbackFunctionPointer = Callback;
}

void max7219_set_shutdown_mode_Stub(CMOCK_max7219_set_shutdown_mode_CALLBACK Callback)
{
  Mock.max7219_set_shutdown_mode_IgnoreBool = (char)0;
  Mock.max7219_set_shutdown_mode_CallbackBool = (char)0;
  Mock.max7219_set_shutdown_mode_CallbackFunctionPointer = Callback;
}

void max7219_set_shutdown_mode_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, int dev_Depth, bool shutdown, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE));
  CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_set_shutdown_mode_CallInstance = CMock_Guts_MemChain(Mock.max7219_set_shutdown_mode_CallInstance, cmock_guts_index);
  Mock.max7219_set_shutdown_mode_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_max7219_set_shutdown_mode(cmock_call_instance, dev, dev_Depth, shutdown);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void max7219_set_shutdown_mode_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, max7219_t const* dev, size_t cmock_size)
{
  CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_set_shutdown_mode_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_dev_Used = 1;
  cmock_call_instance->ReturnThruPtr_dev_Val = dev;
  cmock_call_instance->ReturnThruPtr_dev_Size = cmock_size;
}

void max7219_set_shutdown_mode_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_set_shutdown_mode_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dev = 1;
}

void max7219_set_shutdown_mode_CMockIgnoreArg_shutdown(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_shutdown_mode_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_set_shutdown_mode_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_shutdown = 1;
}

esp_err_t max7219_set_digit(max7219_t* dev, uint8_t digit, uint8_t val)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_max7219_set_digit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_max7219_set_digit);
  cmock_call_instance = (CMOCK_max7219_set_digit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.max7219_set_digit_CallInstance);
  Mock.max7219_set_digit_CallInstance = CMock_Guts_MemNext(Mock.max7219_set_digit_CallInstance);
  if (Mock.max7219_set_digit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.max7219_set_digit_FinalReturn;
    memcpy((void*)(&Mock.max7219_set_digit_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.max7219_set_digit_CallbackBool &&
      Mock.max7219_set_digit_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.max7219_set_digit_CallbackFunctionPointer(dev, digit, val, Mock.max7219_set_digit_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_dev)
  {
    UNITY_SET_DETAILS(CMockString_max7219_set_digit,CMockString_dev);
    if (cmock_call_instance->Expected_dev == NULL)
      { UNITY_TEST_ASSERT_NULL(dev, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_dev), (void*)(dev), sizeof(max7219_t), cmock_call_instance->Expected_dev_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_digit)
  {
    UNITY_SET_DETAILS(CMockString_max7219_set_digit,CMockString_digit);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_digit, digit, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_val)
  {
    UNITY_SET_DETAILS(CMockString_max7219_set_digit,CMockString_val);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_val, val, cmock_line, CMockStringMismatch);
  }
  if (Mock.max7219_set_digit_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.max7219_set_digit_CallbackFunctionPointer(dev, digit, val, Mock.max7219_set_digit_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_dev_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(dev, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)dev, (const void*)cmock_call_instance->ReturnThruPtr_dev_Val,
      cmock_call_instance->ReturnThruPtr_dev_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_max7219_set_digit(CMOCK_max7219_set_digit_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, int dev_Depth, uint8_t digit, uint8_t val);
void CMockExpectParameters_max7219_set_digit(CMOCK_max7219_set_digit_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, int dev_Depth, uint8_t digit, uint8_t val)
{
  cmock_call_instance->Expected_dev = dev;
  cmock_call_instance->Expected_dev_Depth = dev_Depth;
  cmock_call_instance->IgnoreArg_dev = 0;
  cmock_call_instance->ReturnThruPtr_dev_Used = 0;
  cmock_call_instance->Expected_digit = digit;
  cmock_call_instance->IgnoreArg_digit = 0;
  cmock_call_instance->Expected_val = val;
  cmock_call_instance->IgnoreArg_val = 0;
}

void max7219_set_digit_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_set_digit_CALL_INSTANCE));
  CMOCK_max7219_set_digit_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_digit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_set_digit_CallInstance = CMock_Guts_MemChain(Mock.max7219_set_digit_CallInstance, cmock_guts_index);
  Mock.max7219_set_digit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.max7219_set_digit_IgnoreBool = (char)1;
}

void max7219_set_digit_CMockStopIgnore(void)
{
  if(Mock.max7219_set_digit_IgnoreBool)
    Mock.max7219_set_digit_CallInstance = CMock_Guts_MemNext(Mock.max7219_set_digit_CallInstance);
  Mock.max7219_set_digit_IgnoreBool = (char)0;
}

void max7219_set_digit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, uint8_t digit, uint8_t val, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_set_digit_CALL_INSTANCE));
  CMOCK_max7219_set_digit_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_digit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_set_digit_CallInstance = CMock_Guts_MemChain(Mock.max7219_set_digit_CallInstance, cmock_guts_index);
  Mock.max7219_set_digit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_max7219_set_digit(cmock_call_instance, dev, 1, digit, val);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void max7219_set_digit_AddCallback(CMOCK_max7219_set_digit_CALLBACK Callback)
{
  Mock.max7219_set_digit_IgnoreBool = (char)0;
  Mock.max7219_set_digit_CallbackBool = (char)1;
  Mock.max7219_set_digit_CallbackFunctionPointer = Callback;
}

void max7219_set_digit_Stub(CMOCK_max7219_set_digit_CALLBACK Callback)
{
  Mock.max7219_set_digit_IgnoreBool = (char)0;
  Mock.max7219_set_digit_CallbackBool = (char)0;
  Mock.max7219_set_digit_CallbackFunctionPointer = Callback;
}

void max7219_set_digit_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, int dev_Depth, uint8_t digit, uint8_t val, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_set_digit_CALL_INSTANCE));
  CMOCK_max7219_set_digit_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_digit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_set_digit_CallInstance = CMock_Guts_MemChain(Mock.max7219_set_digit_CallInstance, cmock_guts_index);
  Mock.max7219_set_digit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_max7219_set_digit(cmock_call_instance, dev, dev_Depth, digit, val);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void max7219_set_digit_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, max7219_t const* dev, size_t cmock_size)
{
  CMOCK_max7219_set_digit_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_digit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_set_digit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_dev_Used = 1;
  cmock_call_instance->ReturnThruPtr_dev_Val = dev;
  cmock_call_instance->ReturnThruPtr_dev_Size = cmock_size;
}

void max7219_set_digit_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_max7219_set_digit_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_digit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_set_digit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dev = 1;
}

void max7219_set_digit_CMockIgnoreArg_digit(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_max7219_set_digit_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_digit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_set_digit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_digit = 1;
}

void max7219_set_digit_CMockIgnoreArg_val(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_max7219_set_digit_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_set_digit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_set_digit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_val = 1;
}

esp_err_t max7219_clear(max7219_t* dev)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_max7219_clear_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_max7219_clear);
  cmock_call_instance = (CMOCK_max7219_clear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.max7219_clear_CallInstance);
  Mock.max7219_clear_CallInstance = CMock_Guts_MemNext(Mock.max7219_clear_CallInstance);
  if (Mock.max7219_clear_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.max7219_clear_FinalReturn;
    memcpy((void*)(&Mock.max7219_clear_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(esp_err_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.max7219_clear_CallbackBool &&
      Mock.max7219_clear_CallbackFunctionPointer != NULL)
  {
    esp_err_t cmock_cb_ret = Mock.max7219_clear_CallbackFunctionPointer(dev, Mock.max7219_clear_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_dev)
  {
    UNITY_SET_DETAILS(CMockString_max7219_clear,CMockString_dev);
    if (cmock_call_instance->Expected_dev == NULL)
      { UNITY_TEST_ASSERT_NULL(dev, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_dev), (void*)(dev), sizeof(max7219_t), cmock_call_instance->Expected_dev_Depth, cmock_line, CMockStringMismatch); }
  }
  if (Mock.max7219_clear_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.max7219_clear_CallbackFunctionPointer(dev, Mock.max7219_clear_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_dev_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(dev, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)dev, (const void*)cmock_call_instance->ReturnThruPtr_dev_Val,
      cmock_call_instance->ReturnThruPtr_dev_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_max7219_clear(CMOCK_max7219_clear_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, int dev_Depth);
void CMockExpectParameters_max7219_clear(CMOCK_max7219_clear_CALL_INSTANCE* cmock_call_instance, max7219_t* dev, int dev_Depth)
{
  cmock_call_instance->Expected_dev = dev;
  cmock_call_instance->Expected_dev_Depth = dev_Depth;
  cmock_call_instance->IgnoreArg_dev = 0;
  cmock_call_instance->ReturnThruPtr_dev_Used = 0;
}

void max7219_clear_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_clear_CALL_INSTANCE));
  CMOCK_max7219_clear_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_clear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_clear_CallInstance = CMock_Guts_MemChain(Mock.max7219_clear_CallInstance, cmock_guts_index);
  Mock.max7219_clear_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.max7219_clear_IgnoreBool = (char)1;
}

void max7219_clear_CMockStopIgnore(void)
{
  if(Mock.max7219_clear_IgnoreBool)
    Mock.max7219_clear_CallInstance = CMock_Guts_MemNext(Mock.max7219_clear_CallInstance);
  Mock.max7219_clear_IgnoreBool = (char)0;
}

void max7219_clear_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_clear_CALL_INSTANCE));
  CMOCK_max7219_clear_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_clear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_clear_CallInstance = CMock_Guts_MemChain(Mock.max7219_clear_CallInstance, cmock_guts_index);
  Mock.max7219_clear_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_max7219_clear(cmock_call_instance, dev, 1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(esp_err_t[sizeof(cmock_to_return) == sizeof(esp_err_t) ? 1 : -1])); /* add esp_err_t to :treat_as_array if this causes an error */
}

void max7219_clear_AddCallback(CMOCK_max7219_clear_CALLBACK Callback)
{
  Mock.max7219_clear_IgnoreBool = (char)0;
  Mock.max7219_clear_CallbackBool = (char)1;
  Mock.max7219_clear_CallbackFunctionPointer = Callback;
}

void max7219_clear_Stub(CMOCK_max7219_clear_CALLBACK Callback)
{
  Mock.max7219_clear_IgnoreBool = (char)0;
  Mock.max7219_clear_CallbackBool = (char)0;
  Mock.max7219_clear_CallbackFunctionPointer = Callback;
}

void max7219_clear_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, max7219_t* dev, int dev_Depth, esp_err_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_max7219_clear_CALL_INSTANCE));
  CMOCK_max7219_clear_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_clear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.max7219_clear_CallInstance = CMock_Guts_MemChain(Mock.max7219_clear_CallInstance, cmock_guts_index);
  Mock.max7219_clear_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_max7219_clear(cmock_call_instance, dev, dev_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void max7219_clear_CMockReturnMemThruPtr_dev(UNITY_LINE_TYPE cmock_line, max7219_t const* dev, size_t cmock_size)
{
  CMOCK_max7219_clear_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_clear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_clear_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_dev_Used = 1;
  cmock_call_instance->ReturnThruPtr_dev_Val = dev;
  cmock_call_instance->ReturnThruPtr_dev_Size = cmock_size;
}

void max7219_clear_CMockIgnoreArg_dev(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_max7219_clear_CALL_INSTANCE* cmock_call_instance = (CMOCK_max7219_clear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.max7219_clear_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dev = 1;
}

