name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install tools
      run: |
        mkdir $HOME/espressif
        cd $HOME/espressif
        wget https://github.com/jepler/esp-open-sdk/releases/download/2018-06-10/xtensa-lx106-elf-standalone.tar.gz
        tar zxvf xtensa-lx106-elf-standalone.tar.gz
        rm xtensa-lx106-elf/bin/esptool.py
        
        
    - name: update repos
      run: |
        git submodule update --init lib/micropython
        make -C lib/micropython/mpy-cross
        
    - name: make submodules    
      working-directory: lib/micropython
      run: make -C ports/esp8266 submodules
        
    - name: Compile firmware
      run: |
        echo "$HOME/espressif/xtensa-lx106-elf/bin" >> $GITHUB_PATH
        chmod +x $HOME/espressif/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc
        $HOME/espressif/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc -v
        make

    - name: Check output
      run: ls -al build/firmware.bin
