name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile in docker container
      uses: addnab/docker-run-action@v3
      with:
        image: larsks/esp-open-sdk
        options: -v ${{github.workspace}}:/usr
        run: /
            git submodule update --init lib/micropython
            make -C lib/micropython/mpy-cross
            make -C ports/esp8266 submodules
            make

    - name: Check output
      run: ls -al build/firmware.bin
