name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Exporting xtensa gcc path
      run: echo "ESP_ESPRESSIF_ROOT=/usr/lib/espressif" >> $GITHUB_ENV

    - name: Install tools
      run: |
        sudo mkdir /usr/lib/espressif
        # wget https://dl.espressif.com/dl/xtensa-lx106-elf-gcc8_4_0-esp-2020r3-linux-amd64.tar.gz
        wget https://github.com/jepler/esp-open-sdk/releases/download/2018-06-10/xtensa-lx106-elf-standalone.tar.gz
        sudo tar zxvf xtensa-lx106-elf-standalone.tar.gz -C /usr/lib/espressif
        sudo rm /usr/lib/espressif/xtensa-lx106-elf/bin/esptool.py
        
    - name: update repos
      run: |
        git submodule update --init lib/micropython
        make -C lib/micropython/mpy-cross
        
    - name: make submodules    
      working-directory: lib/micropython
      run: make -C ports/esp8266 submodules
        
    - name: Compile firmware
      run: |
        echo "${{ env.ESP_ESPRESSIF_ROOT}}/xtensa-lx106-elf/bin" >> $GITHUB_PATH
        # chmod +x $HOME/espressif/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc
        /usr/lib/espressif/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc -v
        echo $GITHUB_PATH
        ln -s /usr/lib/espressif/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc xtensa-lx106-elf-gcc
        xtensa-lx106-elf-gcc -v
        # ln -s $HOME/espressif/xtensa-lx106-elf/bin/xtensa-lx106-elf-gcc xtensa-lx106-elf-gcc
        make

    - name: Check output
      run: ls -al build/firmware.bin
